### ISSUE TITLE
Broken pdf slides

### ISSUE THREAD

**Issue by biggzlar** [philipphennig/NumericsOfML#8]
Hi there,

thanks for sharing the materials of the lecture. It appears the pdf files are broken when downloaded (tested under macos and ubuntu using various viewers and browsers). The display inside github is working well, curiously. If this is intended, please ignore.

**Comment by philipphennig** [comment]
I just checked with a random pdf, which worked for me. Can you point to a particular file?

**Comment by biggzlar** [comment]
My bad, I did not see that they were stored with lfs. Thanks for the quick response!
